### ISSUE TITLE
Charts aren't displayed in django admin view?

### ISSUE THREAD

**Issue by AzyCrw4282** [puikinsh/CoolAdmin#14]
I am trying to integrate this tempalte to my admin view using django but for some reason none of the charts are displayed, everything else works. Any helps on this would be appreciated. See the image for more reference.
<img width="1392" alt="Screenshot 2019-07-23 at 13 14 45" src="https://user-images.githubusercontent.com/35489636/61724995-e7477480-ad66-11e9-9c3b-4ca1bd37c02b.png">

**Comment by harshnagarkar** [comment]
I think it uses chart.js.
https://www.chartjs.org/
You will have to have a js file with datapoints.
Try opening the chrome developer console and inspect the js.
