### ISSUE TITLE
Modifying issues and queries for your CoolAdmin template

### ISSUE THREAD

**Issue by PinaSystems** [puikinsh/CoolAdmin#2]
Hello,nging 

We are trying to change the Font colour and size using Visual Studio. It is happening in Designer, but when we run the project, no change happens. 
Also we would like to make the Menu role driven. for example, if Admin of our .NET applicaiton logs in, he/she u.will see all Menu items. But other users will see only some menu items depending upon their role. Please guide on how can we do it.

Finally, if we want to change the logo, how can we do the same?

Thank yo

**Comment by Matzestyler** [comment]
Hey @PinaSystems I guess u use a webserver for accessing so in your backend you have to check if the Logged in User have the following rule and shows all items so it will only echo or print the items. With a lower role you echo or print less items or a selected set of items. 

in PHP it would be something like this:
`if($user->getRole() == "Admin") {
echo $fullmenu;
} else {
echo $minmenu;
}` 
It's a example nothing more.
