### ISSUE TITLE
How can I keep the left sidebar dropdown menu?

### ISSUE THREAD

**Issue by hellowkc12** [puikinsh/CoolAdmin#22]
When I click on another menu in the sidebar menu to move it, I want the drop-down menu on the new page to remain open without closing. But I don't know what to do.

**Comment by harshnagarkar** [comment]
I am not exactly sure what you are trying to say. But for example, if you go to index.html page in this theme you can click dashboard dropdown and pages dropdown in the sidebar, you will see both dropdowns stay open, even if you click something else unless you navigate to a different page.

**Comment by hellowkc12** [comment]
What I want to say is that I want the drop-down menu to expand when I go to another page.

**Comment by harshnagarkar** [comment]
Yeah, you would have to create custom triggers, in js.

**Comment by hellowkc12** [comment]
no~~~~
