### ISSUE TITLE
Modal goes behind the header and Fade screen

### ISSUE THREAD

**Issue by srehmanali** [puikinsh/CoolAdmin#24]
Hi, I have implemented this template to the asp.net mvc project and it works pretty good. There is one issue I came across while incorporating the model to my page. I have a layout view where I have all the master page content and the main content goes to individual view. When I tried to call the modal with the following code;
`<button type="button" class="btn btn-secondary mb-1" data-toggle="modal" data-target="#mediumModal">
											Medium
										</button>`

`<div class="modal fade show" id="mediumModal" tabindex="-1" role="dialog" aria-labelledby="mediumModalLabel" style="padding-right: 17px; display: block;">
				<div class="modal-dialog modal-lg" role="document">
					<div class="modal-content">
						<div class="modal-header">
							<h5 class="modal-title" id="mediumModalLabel">Medium Modal</h5>
							<button type="button" class="close" data-dismiss="modal" aria-label="Close">
								<span aria-hidden="true">×</span>
							</button>
						</div>
						<div class="modal-body">
							<p>
								There 
							</p>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
							<button type="button" class="btn btn-primary">Confirm</button>
						</div>
					</div>
				</div>
			</div>`

The modal goes behind the header and the fade screen comes forward so you can not close the modal. Please advise how can we resolve this issue.

image for reference.
![2020-04-28_1033](https://user-images.githubusercontent.com/20923838/80454833-bde1f780-893b-11ea-9d0e-fa69a670916b.png)

Thanks,
Ali

**Comment by harshnagarkar** [comment]
I had the same issue before. You are missing one of the divs. Check this page for example https://github.com/puikinsh/CoolAdmin/blob/master/modal.html.
