### ISSUE TITLE
Problems with opening a simple Href

### ISSUE THREAD

**Issue by dicastropr** [puikinsh/CoolAdmin#4]
Good morning,
I found this dashboard and I liked is very simple and to the point. I made some tweaks to test some random stuff and for some reason I'm having problems with opening a simple Href code. 

Right now I just put the normal a href code to open a Batch program that I create in to a new windows (target="_blank") and doesn't open nothing. The Batch program I have it located in the root where the index.hmtl is located and also in a separated folder inside the root. So far nothing that I had done is worked.

Thanks for the attention and for the help in this topic!

Regards

**Comment by dicastropr** [comment]
Nobody in here?

**Comment by bcattaneo** [comment]
@dicastropr Please post that line of code you're talking about

**Comment by dicastropr** [comment]
@bcattaneo 
![capture](https://user-images.githubusercontent.com/43555178/48497938-7e891f00-e80b-11e8-9004-cabd90ece481.PNG)

**Comment by dicastropr** [comment]
@bcattaneo thanks for the help!

**Comment by youyi1314** [comment]
@dicastropr i think you can try use another link like https://www.google.com/ because browser cant run .bat file.
