### ISSUE TITLE
click on mailto href shows white page because the page thinks it will get redirected

### ISSUE THREAD

**Issue by csskevin** [puikinsh/CoolAdmin#6]
If I create a tag like this and click it
```html
<a href="mailto:someone@example.com">Sometext</a>
```
then the page fades out, because it thinks it redirects. Well, because that is a mailto href the page keeps being white.

For that I have made a workaround:
```html
<a data-href="mailto:someone@example.com" href="#">Sometext</a>
```
and the javascript:
```js
window.addEventListener('load', function() {
   document.querySelectorAll('[data-href]').forEach(function(item) {
      item.addEventListener('click', function(e) {
        window.location = e.target.dataset.href;
      });
    });
});
```

Would be nice if you could fix it. This workaround should help anybody having the same issue.

PS: Might not work in IE, haven't tested it yet.

**Comment by harshnagarkar** [comment]
@puikinsh What do you think about this solution, and should we integrate it?

**Comment by puikinsh** [comment]
@harshnagarkar Sure, why not.

**Comment by csskevin** [comment]
@harshnagarkar @puikinsh 
I wouldn't integrate this as permanent solution. The problem is, that some libraries like Rich Text Editors won't work properly, because they are redirected to a blank page.
For instance:
- Quill Editor
- Form-Builder

**Comment by harshnagarkar** [comment]
@csskevin seems like you have found out the source problem. 
I think like @puikinsh we can integrate this as a temporary solution.

If you find any other solution or come up something, just comment below and we can then merge your fork again. What do you think? @csskevin

**Comment by csskevin** [comment]
@puikinsh @harshnagarkar 
I have created a pull request here: https://github.com/puikinsh/CoolAdmin/pull/17
