### ISSUE TITLE
missing calendar page

### ISSUE THREAD

**Issue by lecar-red** [puikinsh/CoolAdmin#7]
This is a great template. I really like the clean and clear. As i was exploring the demo site and repo, I see a menu item (but href is only empty anchor) but not a sample page. 

Is there suppose to be a calendar page?

**Comment by harshnagarkar** [comment]
@lecar-red  in the commits I see full calendar integration commits, but I don't yet see the calendar, working.
What were you working on, was done with this page?

**Comment by harshnagarkar** [comment]
I pull from main. I was trying to figure out why I don't have it.
Can you please merge your fork with this? @lecar-red

**Comment by lecar-red** [comment]
sorry but i don't have permission to merge with master, you can pull from https://github.com/lecar-red/CoolAdmin and then merge master

**Comment by harshnagarkar** [comment]
Yes, I will do that.

**Comment by harshnagarkar** [comment]
@lecar-red @puikinsh The calendar page has been added. Thanks, Lecar.
